### ISSUE TITLE
Cannot upload ios via appcenter_upload using 1.9.0

### ISSUE THREAD

**Issue by HassanEskandari** [microsoft/fastlane-plugin-appcenter#247]
I am using the following command:
```
    appcenter_upload(
        api_token: ENV["APPCENTER_API_TOKEN"],
        owner_name: ENV["APPCENTER_OWNER_NAME"],
        app_name: ENV["APPCENTER_APP_NAME"],
        file: "PATH-To-IPA",
        release_notes: "RELEASE-NOTES"
        )
````
and it is giving the following error:
```
Client error: 400: {"error"=>{"code"=>400, "message"=>"The request contains invalid content."}}
```

It is working fine with the 1.8.1 version though.

**Comment by mlegenhausen** [comment]
Can confirm the error.

**Comment by codemeister64** [comment]
+1

**Comment by felginep** [comment]
+1

**Comment by 1tatarchuk** [comment]
+1

**Comment by rubenbacanu** [comment]
+1

**Comment by gongracr** [comment]
+1

**Comment by DimaElka** [comment]
+1

**Comment by b3hni4** [comment]
+1

**Comment by shivamkapur** [comment]
+1

**Comment by nascimentorafael** [comment]
+1

**Comment by nascimentorafael** [comment]
+1

**Comment by manuelblum** [comment]
+1

**Comment by ir2pid** [comment]
+1

**Comment by kunal30xi** [comment]
+1

**Comment by diegosalazarCO** [comment]
+1

**Comment by baxri** [comment]
Hey guys I have same issue 

Client error: 400: {"error"=>{"code"=>400, "message"=>"The request contains invalid content."}}

**Comment by mokagio** [comment]
For those using Fastlane via a Bundler, you can lock it to version 2.160.0 like this:

```ruby
# Gemfile

# There is an issue with Fastlane 2.161.0 and the App Center plugin.
# See https://github.com/microsoft/fastlane-plugin-appcenter/issues/247
gem "fastlane", "2.160.0"
```

**Comment by MichalMartinu** [comment]
+1

**Comment by ff-ahumberston** [comment]
Even when dropping back to fastlane 2.160.0 and using fastlane-plugin-appcenter, we are seeing the following error:
Search query: undefined method `length' for nil

Has anybody else experienced this or suggest a possible solution ?

**Comment by mkj-is** [comment]
It's clearly a backend issue with the new upload endpoint. Hopefully, someone from Microsoft gets to fixing this issue soon. Until then, we need to use those older versions.

https://github.com/microsoft/fastlane-plugin-appcenter/commit/e35509d0c326578655cf0870806e770cede30fb7#diff-af4cae5a145a0689c65242cefbb3da5bR65

**Comment by ff-ahumberston** [comment]
Strongly suspect a backend issue, as suggested by @mkj-is 

Even rolling back fails to resolve the issue for myself.

**Comment by ff-ahumberston** [comment]
There has been a newer version of fastlane released earlier (2.162.0), I've not had a chance to test this as yet.  Need to clear a backlog resulting from this issue.

**Comment by omarcande** [comment]
Can confirm from our side: fastlane `2.160.0` works with the latest appcenter plugin, but `2.162.0` throws the error above. Rolling back to appcenter `1.8.1` also solves the problem and works with `2.162.0`.

**Comment by vanlooverenkoen** [comment]
How do I revert back? 

this is added to my PluginFile but 1.9.0 is the used version
```
gem 'fastlane-plugin-appcenter', "1.8.1"
```

**Comment by adityakhatkhate** [comment]
+1

**Comment by rimarsh** [comment]
I believe this issue was introduced by a [change](https://github.com/fastlane/fastlane/commit/7a6b9d684b09c71279daf3471a44bce53a020a53) in fastlane 2.161.0. Previously fastlane was adding a Content-Type header to all requests, even those in plugins. The change made it specific to `apple.com` since that was the original intent, however this plugin appears to have been unintentionally depending on that behavior. I'm able to fix the upload locally by adding the `Content-Type` header to the chunk upload request. I'll open a PR once I do a bit more checking. In the mean time, the change below fixes the failure for me:

<img width="801" alt="Screen Shot 2020-10-01 at 4 18 01 PM" src="https://user-images.githubusercontent.com/5667423/94872582-d0d48880-0401-11eb-8f65-b9362940ca8b.png">

**Comment by kazoobot-kazoo** [comment]
This is how I downgraded to 2.160.0 using homebrew:

brew tap-new kazoo/homebrew
brew extract --version 2.160.0 fastlane kazoo/homebrew
brew uninstall fastlane
brew install kazoo/homebrew/fastlane@2.160.0
fastlane --version

**Comment by redmondurbino** [comment]
This is how I downgraded to 2.160.0 using homebrew:

brew tap-new kazoo/homebrew
brew extract --version 2.160.0 fastlane kazoo/homebrew
brew uninstall fastlane
brew install kazoo/homebrew/fastlane@2.160.0
fastlane --version

**Comment by joshdholtz** [comment]
I commented this in the PR but this was a side effect of a monkey patch that we had in _fastlane_ that would default content type of all requests to `application/json` if not set. We removed this because we shouldn’t have been relying on this in this PR - https://github.com/fastlane/fastlane/pull/17218

Sorry for any issues this may have caused! PR #248 is the correct solution 👍

**Comment by lumaxis** [comment]
I just released `v1.10.0`. Can someone please confirm if it fixes their issue?
Thanks @rimarsh and @joshdholtz for the help with the fix 🥳

**Comment by joshdholtz** [comment]
Np np! Sorry for causing it in the first place 🤷‍♂️😇

**Comment by mrodrig** [comment]
@lumaxis It fixed the issue I was running into with uploads on `1.9.0`. Thanks!

**Comment by ginesdeka** [comment]
`v1.10.0` works fine!!! Thanks!!
